source 'https://rubygems.org'

gem 'dotenv-rails'
gem 'rails', '~> 5.1.3'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.18'

# manageable && translated texts
gem 'globalize', git: 'https://github.com/globalize/globalize'

group :admin do
  # group :admin do
  gem 'activeadmin'
  gem 'activeadmin_addons'
  gem 'activeadmin-globalize', '~> 1.0.0.pre', github: 'fabn/activeadmin-globalize', branch: 'develop'
  # Use Puma as the app server
  gem 'puma', '~> 3.7'

  gem 'whenever', :require => false
end

# Plus integrations with:
gem 'devise'

# gem 'cancan' # or cancancan
# gem 'draper'
# gem 'pundit'

# gem 'trestle'
# end

# group :bot do
# working with http external API's
gem('httparty')

gem('telegram-bot-ruby')
# end

group :development do
  gem('debbie')
end

gem 'activerecord-postgis-adapter'

# google analytics via Google Analytic Measurement Protocol
gem 'staccato'

gem 'proxy_fetcher', '~> 0.5'
